---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    verifier:
      inspect_test:
        - test/recipes
    attributes:
